# Generated by Django 3.0.1 on 2021-10-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=13)),
                ('alternative_contact', models.CharField(max_length=13)),
                ('total_ICU', models.PositiveIntegerField(default=0)),
                ('occupied_ICU', models.PositiveIntegerField(default=0)),
                ('vacant_ICU', models.PositiveIntegerField(default=0)),
                ('total_general', models.PositiveIntegerField(default=0)),
                ('occupied_general', models.PositiveIntegerField(default=0)),
                ('vacant_general', models.PositiveIntegerField(default=0)),
                ('total_oxygen_general', models.PositiveIntegerField(default=0)),
                ('occupied_oxygen_general', models.PositiveIntegerField(default=0)),
                ('vacant_oxygen_general', models.PositiveIntegerField(default=0)),
                ('total_ventilators', models.PositiveIntegerField(default=0)),
                ('total_HDU', models.PositiveIntegerField(default=0)),
                ('occupied_HDU', models.PositiveIntegerField(default=0)),
                ('vacant_HDU', models.PositiveIntegerField(default=0)),
                ('total_isolation_beds', models.PositiveIntegerField(default=0)),
                ('occupied_isolation_beds', models.PositiveIntegerField(default=0)),
                ('vacant_isolation_beds', models.PositiveIntegerField(default=0)),
                ('total_NMC_reserved', models.PositiveIntegerField(default=0)),
                ('occupied_NMC_reserved', models.PositiveIntegerField(default=0)),
                ('vacant_NMC_reserved', models.PositiveIntegerField(default=0)),
                ('location', models.URLField()),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('has_ICU_beds', models.BooleanField()),
                ('has_ventilators', models.BooleanField()),
                ('is_new_hospital', models.BooleanField()),
                ('category', models.CharField(max_length=20)),
                ('total_beds', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_bed.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_bed.State')),
            ],
        ),
    ]
