# Generated by Django 3.0.1 on 2021-10-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_bed', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth.user',
        ),
    ]
