# Generated by Django 3.0.1 on 2021-10-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_bed', '0003_auto_20211027_0007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
