# Generated by Django 3.0.1 on 2021-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_bed', '0005_auto_20211027_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
